apiVersion: v1
kind: Service
metadata:
  name: nodeport-vollmed
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000  # Escolha um número dentro do intervalo permitido
  selector:
    app: vollmed
